package com.example.leahalpert.setsolver.contours;

import org.opencv.core.MatOfPoint;
import org.opencv.core.Point;

/**
 * Created by russell on 12/23/15.
 * Autogenerated by java_converter.py in pyset-goggles
 */
public class Oval {
    public static MatOfPoint contour = new MatOfPoint(new Point(32, 71), new Point(33, 70), new Point(52, 70), new Point(53, 71), new Point(81, 71), new Point(82, 72), new Point(84, 72), new Point(85, 73), new Point(86, 73), new Point(87, 74), new Point(88, 74), new Point(89, 75), new Point(90, 75), new Point(95, 80), new Point(95, 81), new Point(96, 82), new Point(96, 83), new Point(97, 84), new Point(97, 85), new Point(98, 86), new Point(98, 96), new Point(97, 97), new Point(97, 98), new Point(96, 99), new Point(96, 100), new Point(94, 102), new Point(94, 103), new Point(90, 107), new Point(89, 107), new Point(88, 108), new Point(87, 108), new Point(86, 109), new Point(84, 109), new Point(83, 110), new Point(41, 110), new Point(40, 109), new Point(39, 109), new Point(38, 110), new Point(37, 109), new Point(31, 109), new Point(30, 108), new Point(28, 108), new Point(27, 107), new Point(26, 107), new Point(23, 104), new Point(22, 104), new Point(21, 103), new Point(21, 102), new Point(18, 99), new Point(18, 98), new Point(17, 97), new Point(17, 95), new Point(16, 94), new Point(16, 85), new Point(17, 84), new Point(17, 82), new Point(18, 81), new Point(18, 80), new Point(25, 73), new Point(26, 73), new Point(27, 72), new Point(28, 72), new Point(29, 71));
}
